version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - maven-cache:/root/.m2
    command: sleep infinity
    network_mode: service:db
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: customerdb
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data-v3:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"

volumes:
  postgres-data-v3:
  maven-cache: